# Generated by Django 6.0.4 on 2026-05-16 17:44

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_start_year', models.PositiveIntegerField(default=2024, help_text='السنة الميلادية التي بدأت فيها منصة رؤوف عملها.', verbose_name='سنة بداية عمل المنصة')),
                ('doctors_count', models.PositiveIntegerField(default=120, verbose_name='عدد الأطباء المعلن')),
                ('consultations_count', models.PositiveIntegerField(default=5000, verbose_name='عدد الاستشارات الناجحة')),
                ('average_rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=2, verbose_name='متوسط التقييم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعداد الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('user_type', models.CharField(choices=[('owner', 'صاحب قطة'), ('doctor', 'طبيب بيطري')], default='owner', max_length=10, verbose_name='نوع الحساب')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الجوال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='الاسم الكامل')),
                ('license_number', models.CharField(max_length=60, unique=True, verbose_name='رقم الترخيص المهني')),
                ('specialty', models.CharField(max_length=120, verbose_name='التخصص')),
                ('work_start_year', models.PositiveIntegerField(blank=True, help_text='السنة الميلادية التي بدأ فيها الطبيب ممارسة المهنة.', null=True, verbose_name='سنة بداية العمل')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة تعريفية')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='التقييم')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('consultation_price', models.PositiveIntegerField(default=0, verbose_name='سعر الاستشارة (ر.س)')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح الآن')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة الحساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف طبيب',
                'verbose_name_plural': 'ملفات الأطباء',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=120, verbose_name='المعرّف (بريد/جوال)')),
                ('code', models.CharField(max_length=10, verbose_name='الرمز')),
                ('flow', models.CharField(choices=[('register', 'تسجيل مستخدم'), ('doctor-register', 'تسجيل طبيب'), ('forgot', 'استعادة كلمة المرور')], max_length=20, verbose_name='نوع التدفق')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم استخدامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='وقت الانتهاء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز تحقق',
                'verbose_name_plural': 'رموز التحقق',
                'ordering': ['-created_at'],
            },
        ),
    ]
