# Generated by Django 6.0.4 on 2026-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('ended', 'Ended')], default='waiting', max_length=20),
        ),
    ]
