# Generated by Django 6.0.4 on 2026-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0002_alter_videosession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='ice_candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videosession',
            name='offer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='owner_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videosession',
            name='vet_joined',
            field=models.BooleanField(default=False),
        ),
    ]
