# Generated by Django 6.0.4 on 2026-05-11 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0003_videosession_answer_videosession_ice_candidates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
