# Generated by Django 6.0.4 on 2026-05-08 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_scheduled_at_alter_consultation_status'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medications',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='Not specified', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(default='No instructions provided', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.CharField(default='Unknown medication', max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.medicalrecord'),
        ),
    ]
