# Generated by Django 6.0.4 on 2026-05-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
