"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import drf_spectacular
from dotenv import load_dotenv
load_dotenv("../.env")
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6un($ztc452qw&6wgc!%!nqbz8@2kdjajg9lk$h@wdp#j=@-0^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# force rebuild
ALLOWED_HOSTS = [
    "*",
    "portfolioproject-bdyu.onrender.com",
                 ]


# Application definition

INSTALLED_APPS = [
    'daphne',
    "channels",


    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',

    'accounts.apps.AccountsConfig',
    'pets',
    'consultations',
    'payments',
    'medical',
    'video_sessions',

    'rest_framework',
    "rest_framework_simplejwt.token_blacklist",
    'drf_spectacular',  # لإنشاء وثائق API تلقائيًا
    'corsheaders',
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'OPTIONS': {
            'sslmode': 'require',
            'sslrootcert': '/app/certs/ca.pem',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# INTERNAL_IPS = []

AUTH_USER_MODEL = "accounts.User"


# للتجربه فقط يطبع في terminal بدال ارسال ايميلات حقيقية
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = 'Rauf App <no-reply@raufapp.com>'

# اعدادات Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # لارجاع الردود بصيغة JSON
        # لتمكين واجهة التصفح في المتصفح أثناء التطوير
        'rest_framework.renderers.BrowsableAPIRenderer',

    ],
    # لإنشاء وثائق API تلقائيًا
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    "DEFAULT_AUTHENTICATION_CLASSES": (
        # لتمكين التوثيق باستخدام JWT
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    
    'ROTATE_REFRESH_TOKENS': True,                  # تحديث التوكنات بشكل دوري آمن
    'BLACKLIST_AFTER_ROTATION': True,               # وضع التوكن المستهلك في القائمة السوداء للامان
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Rauf API',
    'DESCRIPTION': 'API for Pet Platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"


ASGI_APPLICATION = "config.asgi.application"

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = ['localhost', '127.0.0.1', '0.0.0.0', '*']

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CSRF_TRUSTED_ORIGINS = [
    "https://portfolio-project-eight-olive.vercel.app",
    "https://*.ngrok-free.app",
    "https://*.vercel.app",
    "https://*.railway.app",
    "https://*.onrender.com",
   
    

]
CORS_ALLOWED_ORIGINS = [
    "https://portfolio-project-eight-olive.vercel.app",
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

SECURE_SSL_REDIRECT = False  # في prod تكون True

#channel Backing Store
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(
                os.getenv("REDIS_URL"),
                # os.getenv("REDIS_PORT")
            )],
        },
    },
}


#payments settings
MOYASAR_SECRET_KEY = os.getenv('MOYASAR_SECRET_KEY')


## addmin costumization 
JAZZMIN_SETTINGS = {
    "site_title": "Rauf Admin",
    
    "site_header": "Rauf Clinic",
    
    # "site_logo": "images/logo.png",
    
    "welcome_sign": "Welcome to Rauf Veterinary Clinic Management Portal",
    
    "copyright": "Rauf Vet Clinic Ltd",
    
    "search_model": "accounts.User",

    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "accounts.User"},
    ],
    
    "icons": {
        "accounts.user": "fas fa-users",
        "accounts.profile": "fas fa-user-id",
        "pets.pet": "fas fa-dog",
        "consultations.consultation": "fas fa-calendar-check",
        "medical.medicalrecord": "fas fa-file-medical",
        "payments.paymenttransaction": "fas fa-credit-card",
        "video_sessions.videosession": "fas fa-video",
    },
    
    "show_sidebar": True,
    "navigation_expanded": True,
}

JAZZMIN_UI_TUNER = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark bg-dark", 
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_options": ["sidebar_fixed"],
    "sidebar": "sidebar-dark-primary", 
    "sidebar_nav_flat_style": True,
}

FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://localhost")



