# #TURN Server configration

# listening-port=3478

# lt-cred-mech

# realm=10.61.12.22
# fingerprint


listening-port=3478
tls-listening-port=5349

fingerprint
lt-cred-mech

realm=your-domain.com

user=raufuser:raufpassword123

external-ip=YOUR_PUBLIC_IP

no-loopback-peers
no-multicast-peers
stun-only=false

verbose