# Generated by Django 6.0.4 on 2026-05-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
