# Generated by Django 6.0.4 on 2026-05-23 07:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vetprofile_session_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetprofile',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
