# Generated by Django 6.0.4 on 2026-06-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_vetprofile_session_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
