# Generated by Django 6.0.4 on 2026-05-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vetprofile_session_price'),
        ('consultations', '0002_consultation_scheduled_at_alter_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_consultations', to='accounts.vetprofile'),
        ),
    ]
