# Generated by Django 6.0.4 on 2026-05-18 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_is_paid_consultation_session_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_consultations', to=settings.AUTH_USER_MODEL),
        ),
    ]
