# Build stage
FROM node:20 AS builder

WORKDIR /app

COPY ../frontend/package*.json ./
RUN npm install

COPY ../frontend ./
RUN npm run build

# Serve stage
FROM nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./docker/nginx.conf /etc/nginx/nginx.conf

EXPOSE 443