openapi: 3.0.3
info:
  title: Rauf API
  version: 1.0.0
  description: API for Pet Platform
paths:
  /api/v1/accounts/login/:
    post:
      operationId: v1_accounts_login_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/accounts/logout/:
    post:
      operationId: v1_accounts_logout_create
      tags:
      - v1
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/accounts/profile/:
    get:
      operationId: v1_accounts_profile_retrieve
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: v1_accounts_profile_update
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/v1/accounts/register/:
    post:
      operationId: v1_accounts_register_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                message: User created
          description: ''
  /api/v1/accounts/verify-email/{token}/:
    get:
      operationId: v1_accounts_verify_email_retrieve
      parameters:
      - in: path
        name: token
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/pets/:
    get:
      operationId: v1_pets_list
      description: |-
        GET:
            - pet_owner  يشوف pets حقته فقط
            - vet / admin  يشوفون الكل

        POST:
            - فقط pet_owner
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
          description: ''
    post:
      operationId: v1_pets_create
      description: |-
        GET:
            - pet_owner  يشوف pets حقته فقط
            - vet / admin  يشوفون الكل

        POST:
            - فقط pet_owner
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
  /api/v1/pets/{id}/:
    get:
      operationId: v1_pets_retrieve
      description: |-
        GET:
            - owner + vet + admin

        UPDATE / DELETE:
            - فقط owner
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    put:
      operationId: v1_pets_update
      description: |-
        GET:
            - owner + vet + admin

        UPDATE / DELETE:
            - فقط owner
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    patch:
      operationId: v1_pets_partial_update
      description: |-
        GET:
            - owner + vet + admin

        UPDATE / DELETE:
            - فقط owner
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPet'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    delete:
      operationId: v1_pets_destroy
      description: |-
        GET:
            - owner + vet + admin

        UPDATE / DELETE:
            - فقط owner
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
      - email
      - password
    PatchedPet:
      type: object
      description: |-
        Serializer لتحويل بيانات Pet:
        - من Model → JSON (response)
        - من JSON → Model (request)
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        type:
          type: string
          maxLength: 50
        birth_year:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        created_at:
          type: string
          format: date-time
          readOnly: true
        owner:
          type: integer
          readOnly: true
    Pet:
      type: object
      description: |-
        Serializer لتحويل بيانات Pet:
        - من Model → JSON (response)
        - من JSON → Model (request)
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        type:
          type: string
          maxLength: 50
        birth_year:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        created_at:
          type: string
          format: date-time
          readOnly: true
        owner:
          type: integer
          readOnly: true
      required:
      - birth_year
      - created_at
      - id
      - name
      - owner
      - type
    Register:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
          minLength: 8
        role:
          $ref: '#/components/schemas/RoleEnum'
      required:
      - email
      - password
      - role
    RoleEnum:
      enum:
      - pet_owner
      - vet
      - admin
      type: string
      description: |-
        * `pet_owner` - Pet Owner
        * `vet` - Veterinarian
        * `admin` - Admin
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
